# Generated by Django 6.1 on 2026-08-14 02:03

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
