"""
Django settings for music_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# ============================================================================
# مسیرهای پایه پروژه
# ============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# امنیت (در تولید این مقادیر را تغییر دهید)
# ============================================================================
SECRET_KEY = 'django-insecure-&8x4*7y@!k1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f'
DEBUG = True
ALLOWED_HOSTS = ['*']  # در تولید: ['yourdomain.com', 'www.yourdomain.com']

# ============================================================================
# تعریف اپلیکیشن‌های نصب‌شده
# ============================================================================
INSTALLED_APPS = [
    # Django built-in
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',  # برای مستندسازی API (اختیاری)
    'django_filters',
    
    # Local apps (اپلیکیشن‌های خودمان)
    'apps.core',          # ابزارها و کلاس‌های مشترک
    'apps.users',         # مدیریت کاربران و احراز هویت
    'apps.music',         # آهنگ‌ها و آلبوم‌ها
    'apps.playlists',     # پلی‌لیست‌ها
    # 'apps.notifications', # اعلان‌ها
    'apps.subscriptions', # اشتراک‌ها
    'apps.payments',      # پرداخت‌ها
    'apps.reports',
    # 'apps.admin_panel',   # پنل مدیریت
    # 'apps.tickets',       # تیکت‌های پشتیبانی
    # 'apps.financial',     # حسابرسی مالی
    'corsheaders'
]

# ============================================================================
# میان‌افزارها (Middleware)
# ============================================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS باید در بالاترین جای ممکن باشد
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================================
# تنظیمات مسیرهای اصلی
# ============================================================================
ROOT_URLCONF = 'music_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'music_backend.wsgi.application'

# ============================================================================
# پایگاه داده (در تولید از PostgreSQL استفاده کنید)
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================================
# اعتبارسنجی رمز عبور (تنظیمات پیش‌فرض Django)
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================================
# بین‌المللی‌سازی (زبان و زمان)
# ============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# درگاه پرداخت
# ============================================================================
# تنظیمات زرین‌پال
ZARINPAL_MERCHANT_ID = 'eaa46b01-819e-42ef-8a67-ba2bb7f69a32'  # برای sandbox از 'test' استفاده کنید
ZARINPAL_SANDBOX = True  # برای محیط آزمایشی
ZARINPAL_CALLBACK_URL = 'http://127.0.0.1:3000/api/payments/verify/'  # آدرس بازگشت
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',  # یا 'WARNING' یا 'INFO'
    },
}
# ============================================================================

# ============================================================================
# فایل‌های استاتیک و رسانه (Media)
# ============================================================================
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   # فایل‌های آپلودی اینجا ذخیره می‌شوند
MAX_UPLOAD_SIZE = 50 * 1024 * 1024
# ============================================================================
# مدل کاربر سفارشی
# ============================================================================
AUTH_USER_MODEL = 'users.User'

# ============================================================================
# تنظیمات Django REST Framework
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

# ============================================================================
# تنظیمات JWT (JSON Web Token)
# ============================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ============================================================================
# تنظیمات CORS (Cross-Origin Resource Sharing)
# ============================================================================
# برای توسعه: اجازه به همه دامنه‌ها
CORS_ALLOW_ALL_ORIGINS = True

# برای تولید: لیست دامنه‌های مجاز را مشخص کنید
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
#     'https://yourdomain.com',
# ]

# ============================================================================
# کلید پیش‌فرض فیلدهای AutoField
# ============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# تنظیمات ارسال ایمیل (برای بازیابی رمز عبور و اطلاع‌رسانی‌ها)
# ============================================================================
# برای توسعه: ایمیل‌ها در کنسول لاگ می‌شوند
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# در تولید: از تنظیمات SMTP واقعی استفاده کنید
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'