# Generated by Django 6.1 on 2026-08-14 02:03

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
