# Generated by Django 6.1 on 2026-08-14 02:03

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/', validators=[apps.core.validators.validate_audio_file, apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
