# Generated by Django 6.1 on 2026-08-13 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_playlists', models.IntegerField(blank=True, null=True)),
                ('max_streams_per_day', models.IntegerField(blank=True, null=True)),
                ('can_upload_profile', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('early_access', models.BooleanField(default=False)),
                ('show_analytics', models.BooleanField(default=False)),
                ('default_duration_months', models.IntegerField(default=1, help_text='مدت زمان اعتبار اشتراک بر حسب ماه (پیش\u200cفرض برای خرید)')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
